--------------------------------------------------------
--  파일이 생성됨 - 월요일-7월-27-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table T_CUSTOMER
--------------------------------------------------------

  CREATE TABLE "HR"."T_CUSTOMER" 
   (	"CUS_NO" NUMBER(10,0), 
	"NM" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_ORDER
--------------------------------------------------------

  CREATE TABLE "HR"."T_ORDER" 
   (	"O_NO" NUMBER(10,0), 
	"CUS_NO" NUMBER(10,0), 
	"O_DATE" DATE, 
	"O_PRICE" NUMBER(8,1) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into HR.T_CUSTOMER
SET DEFINE OFF;
Insert into HR.T_CUSTOMER (CUS_NO,NM) values (3,'홍길동');
Insert into HR.T_CUSTOMER (CUS_NO,NM) values (5,'장보고');
REM INSERTING into HR.T_ORDER
SET DEFINE OFF;
Insert into HR.T_ORDER (O_NO,CUS_NO,O_DATE,O_PRICE) values (1,3,to_date('17/07/04','RR/MM/DD'),55000);
Insert into HR.T_ORDER (O_NO,CUS_NO,O_DATE,O_PRICE) values (3,3,to_date('17/07/06','RR/MM/DD'),60000);
--------------------------------------------------------
--  DDL for Index SYS_C0011092
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SYS_C0011092" ON "HR"."T_CUSTOMER" ("CUS_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0011094
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SYS_C0011094" ON "HR"."T_ORDER" ("O_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table T_CUSTOMER
--------------------------------------------------------

  ALTER TABLE "HR"."T_CUSTOMER" ADD PRIMARY KEY ("CUS_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table T_ORDER
--------------------------------------------------------

  ALTER TABLE "HR"."T_ORDER" MODIFY ("O_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."T_ORDER" ADD PRIMARY KEY ("O_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table T_ORDER
--------------------------------------------------------

  ALTER TABLE "HR"."T_ORDER" ADD FOREIGN KEY ("CUS_NO")
	  REFERENCES "HR"."T_CUSTOMER" ("CUS_NO") ENABLE;
